import { Entity, Column, Index } from 'typeorm';
import { BaseEntity } from '../common/base.entity';
import { TransactionType, TransactionStatus, Currency } from '../common/enums';

@Entity('transactions')
@Index(['reference'], { unique: true })
@Index(['idempotencyKey'], { unique: true })
@Index(['providerReference'])
@Index(['sourceWalletId'])
@Index(['destinationWalletId'])
@Index(['initiatedByUserId', 'createdAt'])
export class Transaction extends BaseEntity {
  /**
   * Human-readable unique reference.
   * Format: TXN-{YYYYMMDD}-{TYPE}-{RANDOM}
   * Example: TXN-20260120-DEP-A3F8K9
   */
  @Column({ unique: true })
  reference: string;

  /**
   * Client-provided idempotency key to prevent duplicate transactions.
   * Should be a UUID v4 generated by the client.
   */
  @Column({ unique: true })
  idempotencyKey: string;

  @Column({
    type: 'enum',
    enum: TransactionType,
  })
  type: TransactionType;

  @Column({
    type: 'enum',
    enum: TransactionStatus,
    default: TransactionStatus.PENDING,
  })
  status: TransactionStatus;

  /**
   * Amount in kobo (smallest unit).
   * ₦100 = 10000 kobo
   */
  @Column({ type: 'bigint' })
  amount: string;

  @Column({
    type: 'enum',
    enum: Currency,
    default: Currency.NGN,
  })
  currency: Currency;

  /**
   * User who initiated this transaction.
   */
  @Column('uuid')
  initiatedByUserId: string;

  /**
   * Source wallet (for withdrawals, transfers).
   * Null for deposits.
   */
  @Column('uuid', { nullable: true })
  sourceWalletId?: string | null;

  /**
   * Destination wallet (for deposits, transfers).
   * Null for withdrawals.
   */
  @Column('uuid', { nullable: true })
  destinationWalletId?: string | null;

  /**
   * External provider reference (e.g., Paystack transaction reference).
   */
  @Column({ type: 'varchar', nullable: true })
  providerReference?: string | null;

  /**
   * Full response from payment provider for audit purposes.
   */
  @Column({ type: 'jsonb', nullable: true })
  providerResponse?: Record<string, any> | null;

  /**
   * Custom metadata attached to the transaction.
   */
  @Column({ type: 'jsonb', nullable: true })
  metadata?: Record<string, any> | null;

  /**
   * Reason for failure if status is FAILED.
   */
  @Column({ type: 'varchar', nullable: true })
  failureReason?: string | null;

  /**
   * Description/narration for the transaction.
   */
  @Column({ type: 'varchar', nullable: true })
  description?: string | null;
}
